In [ ]:
#Kiruthikashree.A

In [1]:
import numpy as np

In [4]:
shree=np.array([10,20,30,40,50])
print("Numpy array")
print(shree)

Numpy array
[10 20 30 40 50]


In [5]:
print("shape of numpy")
print(shree.shape)

shape of numpy
(5,)


In [7]:
import pandas as pd

In [19]:
kavi=pd.Series([1,2,3,4,5])
print(kavi)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [21]:
bhama=np.array([11,22,33,44,55,66,77,88,99,00])
print("Numpy in 1-Dimensional array")
print(bhama)

Numpy in 1-Dimensional array
[11 22 33 44 55 66 77 88 99  0]


In [23]:
rose=np.array([[12,13,14,15],[25,35,45,55]])
print("Numpy in 2-Dimensional array")
print(rose)

Numpy in 2-Dimensional array
[[12 13 14 15]
 [25 35 45 55]]


In [17]:
black=np.zeros((4,5))
print(black)
print("Numpy array in zeros")

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Numpy array in zeros


In [18]:
shash=np.ones((5,4))
print("Numpy array in ones")
print(shash)

Numpy array in ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
